### ISSUE TITLE
Page load time in Firebug is nearly double time displayed in profiler

### ISSUE THREAD

**Issue by keeebs** [fbrnc/Aoe_Profiler#14]
I am loading a product page with all cache's turned off because I'm in development, but the profiler provides a time of 5908ms, but firebug is recording a page load time of 10.12s. On a category page, the profiler states 9702ms, firebug says 16.48s. Could anyone help me understand what could possibly be creating such a significant difference in times? I'm strictly looking at the time to load the page itself. All the static components of the page are being loaded from a cdn. TY

**Comment by Flyingmana** [comment]
the profiler excludes the rendering of itself and does not measure time the webserver needs to send the data to the client and also not the time between request and start of processing. So depending on a lot of factors, firebug will always output more time.

**Comment by fbrnc** [comment]
Hi @keeebs,
@Flyingmana is totally right: Aoe_Profiler will only track what's happening server side and is even trying to exlcude the time it needs to process and display the results. In addition to that the data needs to be send to the browser and rendered there which also adds a little bit of time.
This should explain the difference.
If you thinks there's still something wonky please let me know.
