### ISSUE TITLE
Any plans to port changes/additions back from AOEpeople/Aoe_Profiler

### ISSUE THREAD

**Issue by joh-klein** [fbrnc/Aoe_Profiler#23]
I just saw that the form from AOEpeople is much more current. Do you plan to merge those changes?

**Comment by fbrnc** [comment]
Hi,
development for Aoe_Profiler continues in the aoepeople account. I'll might be deleting this version in the near future.

Cheers,
Fabrizio

**Comment by joh-klein** [comment]
Could you [transfer ownership] (https://help.github.com/articles/transferring-a-repository/) so that issues are available again on the fork? Or at least [check the box on the fork] (http://programmers.stackexchange.com/a/179470) that issues can be posted. Thank you!

**Comment by fbrnc** [comment]
Hi Johannes,

this is actually what I did:
- merged the latest changes from AOEPeople/Aoe_Profiler back to fbrnc/Aoe_Profiler, 
- then I deleted AOEPeople/Aoe_Profiler
- then I transferred ownership from fbrnc/Aoe_Profiler to AOEPeople/Aoe_Profiler

Now there's no fbrnc/Aoe_Profiler anymore and requests are redirected

You should be able to post issues here now (checkboxes is enabled)

**Comment by joh-klein** [comment]
Super geil. Thanks! :)
